"""
Checkpoint management for FSDP models.

Provides:
- Low-level DCP functions (save_checkpoint_dcp, load_checkpoint_dcp, find_latest_checkpoint)
- High-level checkpoint saving (save_checkpoint_if_needed) for core training
"""

import os
import json
import glob
import re
import shutil
from dataclasses import asdict, is_dataclass
import torch
import torch.distributed.checkpoint as dcp
from torch.distributed.checkpoint import FileSystemWriter, FileSystemReader
from torch.distributed.checkpoint.state_dict import get_state_dict, set_state_dict
from typing import List, Optional, Dict, Any


def save_checkpoint_dcp(
    checkpoint_dir: str,
    model,
    optimizers: List,
    meta_data: Dict[str, Any],
    rank: int = 0,
    world_size: int = 1,
    dataloader_state: Optional[Dict] = None,
) -> None:
    """
    Save FSDP checkpoint using DCP.

    Args:
        checkpoint_dir: Directory to save checkpoint (created if not exists)
        model: FSDP model (contains DTensor parameters)
        optimizers: List of optimizers
        meta_data: Dictionary of metadata to save (must include 'step')
        rank: Current rank
        world_size: Total number of ranks
        dataloader_state: Optional dataloader state for resuming

    Saves:
        - checkpoint_dir/.metadata (JSON, generated by DCP)
        - checkpoint_dir/__0_0.distcp, __1_0.distcp, ... (sharded)
        - checkpoint_dir/meta.json (custom metadata + dataloader_state, rank 0 only)
    """
    # Create checkpoint directory
    os.makedirs(checkpoint_dir, exist_ok=True)

    # Use get_state_dict() to properly handle FSDP model and optimizer states
    # Returns tuple: (model_state_dict, optim_state_dict)
    model_state_dict, optim_state_dict = get_state_dict(model, optimizers)

    # Build state_dict for DCP
    state_dict = {
        "model": model_state_dict,
        "optimizer": optim_state_dict,
    }

    # DCP save (all ranks participate, each writes its own shard)
    # overwrite=True: Handle NFS cache inconsistency in multi-node environments
    dcp.save(
        state_dict=state_dict,
        storage_writer=FileSystemWriter(checkpoint_dir, overwrite=True),
    )

    # Save custom metadata (rank 0 only)
    if rank == 0:
        # Merge dataloader_state into metadata if provided
        if dataloader_state is not None:
            meta_data = {**meta_data, 'dataloader_state': dataloader_state}

        # Self-description: record the architecture this checkpoint was trained
        # with (model.config — LMSystem exposes the trunk's GPTConfig). The live
        # model is the ONLY authority for this key, so it is written
        # UNCONDITIONALLY — a caller-supplied 'model_config' is by definition
        # less authoritative than the model being saved. Loaders recover it via
        # gpt_config_from_meta(); _validate_model_config audits every load
        # against it. A config-less model produces an old-format checkpoint
        # (validation skips: you cannot record what does not exist).
        cfg = getattr(model, 'config', None)
        if is_dataclass(cfg):
            meta_data = {**meta_data, 'model_config': asdict(cfg)}
        # Architecture tag: an ASSEMBLY fact recorded by build_system onto the
        # System (type(trunk) at save time would lie — fully_shard rewrites the
        # instance's class to FSDP{ClassName}). Loaders audit the caller's
        # trunk_cls choice against it (load_system's checked default).
        arch = getattr(model, 'arch', None)
        if arch is not None:
            meta_data = {**meta_data, 'model_arch': arch}

        # Runtime attention is not part of state_dict. Projects may attach a
        # JSON-serializable descriptor so inference can restore it explicitly.
        attention_config = getattr(model, 'attention_config', None)
        if isinstance(attention_config, dict):
            meta_data = {**meta_data, 'attention_config': dict(attention_config)}

        meta_path = os.path.join(checkpoint_dir, "meta.json")
        with open(meta_path, "w") as f:
            json.dump(meta_data, f, indent=2)


def load_checkpoint_dcp(
    checkpoint_dir: str,
    model,
    load_optimizer: bool = False,
    optimizers: Optional[List] = None,
    rank: int = 0,
    world_size: int = 1,
) -> Dict[str, Any]:
    """
    Load FSDP checkpoint using DCP.

    Args:
        checkpoint_dir: Directory containing checkpoint
        model: FSDP model (will be filled with loaded weights)
        load_optimizer: Whether to load optimizer state
        optimizers: List of optimizers to load into (if load_optimizer=True)
        rank: Current rank
        world_size: Total number of ranks

    Returns:
        meta_data: Dictionary of metadata loaded from checkpoint

    Side effects:
        - model parameters are updated in-place
        - optimizer states are updated in-place (if load_optimizer=True)

    Raises:
        ValueError: If checkpoint model_config doesn't match model's config
    """
    # Validate model config before loading
    _validate_model_config(checkpoint_dir, model, rank)

    # Use get_state_dict() to create proper template structure
    # This handles fresh optimizers correctly by constructing the full state structure
    opt_list = optimizers if (load_optimizer and optimizers is not None) else None
    model_state_dict, optim_state_dict = get_state_dict(model, opt_list)

    # Build state_dict for DCP load
    state_dict = {
        "model": model_state_dict,
        "optimizer": optim_state_dict if load_optimizer else None,
    }

    # DCP load (all ranks participate, each reads its own shard)
    dcp.load(
        state_dict=state_dict,
        storage_reader=FileSystemReader(checkpoint_dir),
    )

    # Use set_state_dict() to properly load into model and optimizer
    # This handles DTensor conversion and optimizer state restoration correctly
    set_state_dict(
        model,
        opt_list,
        model_state_dict=state_dict["model"],
        optim_state_dict=state_dict.get("optimizer") if load_optimizer else None,
    )

    # Load custom metadata
    meta_path = os.path.join(checkpoint_dir, "meta.json")
    with open(meta_path, "r") as f:
        meta_data = json.load(f)

    return meta_data


def load_metadata(checkpoint_dir: str) -> Dict[str, Any]:
    """
    Load only metadata from checkpoint without loading model/optimizer weights.

    Args:
        checkpoint_dir: Directory containing checkpoint

    Returns:
        meta_data: Dictionary of metadata from checkpoint
    """
    meta_path = os.path.join(checkpoint_dir, "meta.json")
    with open(meta_path, "r") as f:
        meta_data = json.load(f)
    return meta_data


def get_model_config(checkpoint_dir: str) -> Optional[Dict[str, Any]]:
    """
    Get model config from checkpoint metadata.

    Args:
        checkpoint_dir: Directory containing checkpoint

    Returns:
        The recorded model config dict (asdict of the GPTConfig the checkpoint
        was trained with) or None if not available (old checkpoint format)
    """
    meta = load_metadata(checkpoint_dir)
    return meta.get('model_config')


def config_from_meta(checkpoint_dir: str, config_cls, sequence_len: Optional[int] = None):
    """Blueprint recovery: rebuild the config a checkpoint was trained with.

    The inverse of the save-side recording (save_checkpoint_dcp writes
    asdict(model.config) into meta.json['model_config']). Keeping BOTH sides
    of this schema round-trip in core is what stops consumers from re-deriving
    architecture by convention. `config_cls` names the dataclass to rebuild
    into — callers get it from the trunk contract (trunk_cls.Config), so core
    stays ignorant of concrete architectures. `sequence_len` may be
    overridden — an instantiation choice (RoPE tables are computed, not
    stored), not a weight fact; everything else comes from the artifact.

    Returns None for old checkpoints that predate self-description.
    """
    saved = get_model_config(checkpoint_dir)
    if saved is None:
        return None
    # Tolerate schema drift both ways: unknown recorded keys are dropped,
    # fields newer than the recording fall back to config_cls defaults.
    known = {k: v for k, v in saved.items() if k in config_cls.__dataclass_fields__}
    if sequence_len is not None:
        known['sequence_len'] = sequence_len
    return config_cls(**known)


def gpt_config_from_meta(checkpoint_dir: str, sequence_len: Optional[int] = None):
    """config_from_meta specialized to GPTConfig (the name predates the
    trunk_cls seam; kept because it is honest — it does build a GPTConfig)."""
    from core.model.gpt import GPTConfig
    return config_from_meta(checkpoint_dir, GPTConfig, sequence_len=sequence_len)


def _validate_model_config(checkpoint_dir: str, model, rank: int = 0) -> None:
    """
    Validate that checkpoint model_config matches the model's config.

    Raises:
        ValueError: If configs don't match (with clear error message)
    """
    saved_config = get_model_config(checkpoint_dir)
    if saved_config is None:
        # Old checkpoint format, skip validation
        return

    if not hasattr(model, 'config'):
        # Model doesn't have config attribute, skip validation
        return

    cfg = model.config
    mismatches = []

    # Architecture identity — strictest of all: same config fields on a
    # different wiring is the ultimate "silently wrong model". Audited only
    # when both sides carry the fact (old checkpoints / bare models don't).
    saved_arch = load_metadata(checkpoint_dir).get('model_arch')
    model_arch = getattr(model, 'arch', None)
    if saved_arch is not None and model_arch is not None and saved_arch != model_arch:
        mismatches.append(f"model_arch: checkpoint={saved_arch}, model={model_arch}")

    # WEIGHT-SHAPING facts — these define what the stored tensors ARE. Some
    # mismatches would not even raise a shape error (n_head reshapes nothing,
    # yet changes attention semantics — a silently wrong model), so all are
    # strictly enforced.
    for field in ('n_layer', 'n_embd', 'n_head', 'n_kv_head', 'vocab_size', 'n_token_types'):
        if field in saved_config and saved_config[field] != getattr(cfg, field, None):
            mismatches.append(
                f"{field}: checkpoint={saved_config[field]}, model={getattr(cfg, field, None)}")

    if mismatches:
        raise ValueError(
            f"Model config mismatch with checkpoint {checkpoint_dir}:\n  " +
            "\n  ".join(mismatches)
        )

    # sequence_len is an INSTANTIATION choice, not a weight fact (RoPE tables
    # are computed, not stored) — running at a different context length than
    # trained is legitimate (e.g. short-context inference). Inform, don't block.
    if saved_config.get('sequence_len') != cfg.sequence_len and rank == 0:
        print(f"  note: sequence_len differs from checkpoint "
              f"(checkpoint={saved_config.get('sequence_len')}, model={cfg.sequence_len}) "
              f"— allowed (instantiation choice)")


def load_model_only(
    checkpoint_dir: str,
    model,
    rank: int = 0,
    world_size: int = 1,
) -> None:
    """
    Load only model weights from checkpoint (for pretrained initialization).

    Optimizer and dataloader states are NOT loaded - training starts fresh.
    Use this for initializing a new training run from pretrained weights.

    Args:
        checkpoint_dir: Directory containing checkpoint
        model: FSDP model (will be filled with loaded weights)
        rank: Current rank
        world_size: Total number of ranks

    Side effects:
        - model parameters are updated in-place
        - optimizer and dataloader states are ignored

    Raises:
        ValueError: If checkpoint model_config doesn't match model's config
    """
    # Validate model config before loading
    _validate_model_config(checkpoint_dir, model, rank)

    # Use get_state_dict() to create proper template structure for model only
    # Pass empty list instead of None (get_state_dict expects iterable)
    model_state_dict, _ = get_state_dict(model, optimizers=[])

    # Build state_dict for DCP load (model only)
    state_dict = {
        "model": model_state_dict,
    }

    # DCP load (all ranks participate, each reads its own shard)
    dcp.load(
        state_dict=state_dict,
        storage_reader=FileSystemReader(checkpoint_dir),
    )

    # Use set_state_dict() to properly load into model
    # Pass empty list instead of None (set_state_dict expects iterable)
    set_state_dict(
        model,
        optimizers=[],
        model_state_dict=state_dict["model"],
        optim_state_dict=None,
    )

    print(f"[Rank {rank}] Loaded model weights from {checkpoint_dir}")


def find_latest_checkpoint(base_dir: str) -> Optional[str]:
    """
    Find the latest checkpoint directory in base_dir.

    Args:
        base_dir: Base directory containing checkpoint directories

    Returns:
        Path to latest checkpoint directory, or None if not found

    Example:
        base_dir = "/path/to/checkpoints"
        latest = find_latest_checkpoint(base_dir)
        # Returns: "/path/to/checkpoints/step_002000"
    """
    import glob
    import re

    if not os.path.exists(base_dir):
        return None

    # Find all step_* directories
    pattern = os.path.join(base_dir, "step_*")
    checkpoint_dirs = glob.glob(pattern)

    if not checkpoint_dirs:
        return None

    # Extract step numbers and sort
    checkpoints = []
    for path in checkpoint_dirs:
        dirname = os.path.basename(path)
        match = re.fullmatch(r"step_(\d+)", dirname)
        if match:
            step = int(match.group(1))
            checkpoints.append((step, path))

    if not checkpoints:
        return None

    # Return the checkpoint with highest step number
    checkpoints.sort(key=lambda x: x[0], reverse=True)
    return checkpoints[0][1]


def resolve_checkpoint_path(
    resume_from: Optional[str],
    save_dir: Optional[str] = None,
    rank: int = 0
) -> Optional[str]:
    """
    Intelligently resolve checkpoint path with auto-detection support.

    This function provides smart checkpoint path resolution:
    1. If resume_from is None/empty -> return None (afresh run)
    2. If resume_from == "auto" -> check save_dir for latest checkpoint
       - If save_dir has checkpoints -> return latest
       - If save_dir doesn't exist or has no checkpoints -> return None (afresh run)
    3. If resume_from is an explicit path:
       - If path doesn't exist -> raise FileNotFoundError (fail-fast)
       - If path is a DCP checkpoint -> return it directly
       - If path is a directory with step_* subdirs -> auto-detect latest
       - Otherwise -> raise FileNotFoundError

    Args:
        resume_from: Path to checkpoint, directory, or "auto"
        save_dir: Directory where checkpoints are saved (required for "auto" mode)
        rank: Current rank (for printing messages on rank 0 only)

    Returns:
        Resolved checkpoint path, or None if no checkpoint found

    Raises:
        FileNotFoundError: If explicit path doesn't exist (fail-fast to prevent training mistakes)
        ValueError: If resume_from is "auto" but save_dir is not provided

    Examples:
        # Auto-resume mode (afresh if no checkpoint, resume if found)
        resolve_checkpoint_path("auto", save_dir="checkpoints/d12_run1")
        # Prints: "🔄 Auto-resume: Found checkpoint in checkpoints/d12_run1"
        # Returns: "checkpoints/d12_run1/step_002000" (or None if no checkpoint)

        # Explicit DCP checkpoint (fail-fast if not found)
        resolve_checkpoint_path("checkpoints/step_001000")
        # Returns: "checkpoints/step_001000" (or raises FileNotFoundError)

        # Explicit directory (auto-detect latest, fail-fast if not found)
        resolve_checkpoint_path("checkpoints/d12_run1")
        # Prints: "📁 Auto-detected latest checkpoint: checkpoints/d12_run1/step_002000"
        # Returns: "checkpoints/d12_run1/step_002000" (or raises FileNotFoundError)

        # No resume
        resolve_checkpoint_path(None)
        # Returns: None
    """
    # Case 1: No resume path provided (afresh run)
    if not resume_from:
        return None

    # Case 2: Auto-resume mode
    if resume_from.lower() == "auto":
        # Auto mode requires save_dir
        if not save_dir:
            raise ValueError(
                "resume_from='auto' requires save_dir to be specified in checkpoint config"
            )

        # Expand environment variables in save_dir
        save_dir = os.path.expandvars(save_dir)

        # Check if save_dir exists
        if not os.path.exists(save_dir):
            # save_dir doesn't exist yet (first run) - start fresh
            if rank == 0:
                print(f"🆕 Auto-resume: No checkpoint directory found")
                print(f"   Directory: {save_dir}")
                print(f"   Starting fresh training")
            return None

        # Try to find latest checkpoint in save_dir
        latest_checkpoint = find_latest_checkpoint(save_dir)
        if latest_checkpoint:
            # Found checkpoint - resume from it
            if rank == 0:
                step_name = os.path.basename(latest_checkpoint)
                print(f"🔄 Auto-resume: Found checkpoint in {save_dir}")
                print(f"   Resuming from: {step_name}")
            return latest_checkpoint
        else:
            # save_dir exists but no checkpoints yet - start fresh
            if rank == 0:
                print(f"🆕 Auto-resume: No checkpoints found in {save_dir}")
                print(f"   Starting fresh training")
            return None

    # Case 3: Explicit path (fail-fast if doesn't exist)
    # Expand environment variables
    resume_from = os.path.expandvars(resume_from)

    # Path must exist (fail-fast to catch typos)
    if not os.path.exists(resume_from):
        raise FileNotFoundError(
            f"Checkpoint path does not exist: {resume_from}\n"
            f"Hint: Use checkpoint.resume_from=auto for automatic resume (will start fresh if no checkpoint exists)"
        )

    # Case 3a: Not a directory (e.g., legacy checkpoint file)
    if not os.path.isdir(resume_from):
        return resume_from

    # Case 3b: Check if it's a DCP checkpoint directory
    # DCP checkpoints have meta.json and .metadata files
    meta_json = os.path.join(resume_from, "meta.json")
    if os.path.exists(meta_json):
        # It's a valid DCP checkpoint, return directly
        return resume_from

    # Case 3c: Check if directory contains step_* subdirectories
    latest_checkpoint = find_latest_checkpoint(resume_from)
    if latest_checkpoint:
        # Auto-detected latest checkpoint
        if rank == 0:
            step_name = os.path.basename(latest_checkpoint)
            print(f"📁 Auto-detected latest checkpoint: {latest_checkpoint}")
            print(f"   (from directory: {resume_from}, latest: {step_name})")
        return latest_checkpoint

    # Case 3d: Directory exists but no checkpoints found (fail-fast)
    raise FileNotFoundError(
        f"Directory exists but contains no valid checkpoints: {resume_from}\n"
        f"Hint: Use checkpoint.resume_from=auto for automatic resume (will start fresh if no checkpoint exists)"
    )


# =============================================================================
# High-level checkpoint handling for core training
# =============================================================================

def should_save_checkpoint(step: int, max_steps: int, save_every: int) -> bool:
    """
    Determine if checkpoint should be saved at current step.

    Args:
        step: Current training step
        max_steps: Total training steps
        save_every: Save frequency (-1 means save only at end)

    Returns:
        bool: True if checkpoint should be saved
    """
    # Always save at the last step
    if step == max_steps - 1:
        return True

    # -1 means save only at the end
    if save_every == -1:
        return False

    # Save at regular intervals
    return step % save_every == 0


def cleanup_old_checkpoints(save_dir: str, keep_last_n: int, current_step: int):
    """
    Remove old checkpoint directories, keeping only the last N.

    Only considers checkpoints with step <= current_step for cleanup.
    Checkpoints with step > current_step (from previous runs) are ignored
    and a warning is printed.

    Args:
        save_dir: Base directory containing checkpoint directories
        keep_last_n: Number of checkpoints to keep (-1 means keep all)
        current_step: Current training step (only cleanup checkpoints <= this step)
    """
    if keep_last_n == -1:
        return

    # Find all step_* directories
    checkpoint_dirs = glob.glob(os.path.join(save_dir, "step_*"))

    # Extract step numbers and categorize
    valid_checkpoints = []  # step <= current_step
    future_checkpoints = []  # step > current_step (from old runs)

    for path in checkpoint_dirs:
        dirname = os.path.basename(path)
        match = re.fullmatch(r"step_(\d+)", dirname)
        if match:
            step = int(match.group(1))
            if step <= current_step:
                valid_checkpoints.append((step, path))
            else:
                future_checkpoints.append((step, path))

    # Warn about future checkpoints (from previous runs)
    from core.utils import print0
    if future_checkpoints:
        future_steps = sorted([step for step, _ in future_checkpoints], reverse=True)
        print0(f"  ⚠️  Found {len(future_checkpoints)} checkpoint(s) with larger steps {future_steps} (keep_last_n won't delete these)")

    # Check if we need to cleanup valid checkpoints
    if len(valid_checkpoints) <= keep_last_n:
        return

    # Sort by step number (newest first)
    valid_checkpoints.sort(key=lambda x: x[0], reverse=True)

    # Remove old checkpoints (only those <= current_step)
    for _, path in valid_checkpoints[keep_last_n:]:
        print0(f"  Removing old checkpoint: {path}")
        shutil.rmtree(path)


def load_checkpoint_if_needed(
    checkpoint_config: Dict[str, Any],
    model,
    optimizers: List,
    dataloader,
    rank: int,
    world_size: int,
) -> tuple[int, Optional[Dict]]:
    """
    Load checkpoint if needed based on configuration.

    Handles checkpoint loading logic with priority:
    1. resume_from (full training resume: model + optimizer + dataloader)
    2. init_model_from (model weights only, fresh training)
    3. No loading (random initialization)

    This is the main interface for checkpoint loading in core training.
    Matches the pattern of save_checkpoint_if_needed for consistency.

    Args:
        checkpoint_config: Checkpoint configuration dict (from config['checkpoint'])
        model: FSDP-wrapped model
        optimizers: List of optimizers
        dataloader: Dataloader (must have set_state() method for resume support)
        rank: Current rank
        world_size: Total number of ranks

    Returns:
        (start_step, trainer_state):
            - start_step: Step to start/resume training from (0 for fresh, N+1 for resume)
            - trainer_state: Trainer internal state from checkpoint (None for fresh training)

    Examples:
        # In Trainer.__init__():
        self.start_step, self._resumed_trainer_state = load_checkpoint_if_needed(
            checkpoint_config=self.checkpoint_config,
            model=self.model,
            optimizers=self.optimizers,
            dataloader=self.dataloader,
            rank=self.rank,
            world_size=self.world_size,
        )
    """
    from core.utils import print0

    resume_from = checkpoint_config.get('resume_from')
    init_model_from = checkpoint_config.get('init_model_from')
    save_dir = checkpoint_config.get('save_dir')

    # Priority 1: Full checkpoint resume (model + optimizer + dataloader)
    if resume_from:
        resolved_path = resolve_checkpoint_path(resume_from, save_dir=save_dir, rank=rank)
        if resolved_path:
            # Load full checkpoint
            if rank == 0:
                print0(f"\nResuming from checkpoint: {resolved_path}")

            metadata = load_checkpoint_dcp(
                checkpoint_dir=resolved_path,
                model=model,
                load_optimizer=True,
                optimizers=optimizers,
                rank=rank,
                world_size=world_size,
            )

            # Resume from saved step (checkpoint at step N → resume at N+1)
            saved_step = metadata['step']
            start_step = saved_step + 1

            # Resume dataloader state if available and supported
            dataloader_state = metadata.get('dataloader_state')
            if dataloader_state and hasattr(dataloader, 'set_state'):
                dataloader.set_state(dataloader_state)
                if rank == 0:
                    sampler = getattr(dataloader, 'sampler', None)
                    print0(f"  ✓ Resumed dataloader state: {sampler}" if sampler else "  ✓ Resumed dataloader state")

            # Extract trainer state for resuming
            trainer_state = metadata.get('trainer_state')

            if rank == 0:
                print0(f"  ✓ Resumed from step {saved_step} checkpoint (will continue from step {start_step})")
                print0("")

            return start_step, trainer_state

        elif init_model_from:
            # resume_from was set but no checkpoint found, fall back to init_model_from
            if rank == 0:
                print0(f"\n⚠️  No checkpoint found for resume_from, falling back to init_model_from")

    # Priority 2: Model weight initialization only (fresh training)
    if init_model_from:
        if isinstance(init_model_from, str) and init_model_from.lower() == "auto":
            raise ValueError(
                "checkpoint.init_model_from does not support 'auto'. "
                "If you want to resume training, use checkpoint.resume_from=auto instead."
            )

        ckpt_path = resolve_checkpoint_path(init_model_from, save_dir=None, rank=rank)
        if ckpt_path is None:
            raise FileNotFoundError(f"Init checkpoint not found: {init_model_from}")

        if rank == 0:
            print0(f"\nInitializing model from checkpoint: {ckpt_path}")
            print0(f"  (Model weights only - optimizer and dataloader start fresh)")

        load_model_only(
            checkpoint_dir=ckpt_path,
            model=model,
            rank=rank,
            world_size=world_size,
        )

        if rank == 0:
            print0(f"  ✓ Model initialized from pretrained weights")
            print0(f"  ✓ Training will start from step 0\n")

        return 0, None

    # Priority 3: No loading (random initialization)
    return 0, None


def save_checkpoint_if_needed(
    step: int,
    model,
    optimizers: List,
    config: Dict[str, Any],
    rank: int,
    world_size: int,
    dataloader_state: Optional[Dict] = None,
    trainer_state: Optional[Dict] = None,
    dataloader=None,
):
    """
    Save checkpoint if needed based on configuration and current step.

    Handles checkpoint saving logic including:
    - Checking if checkpoint should be saved
    - Saving checkpoint using DCP
    - Cleaning up old checkpoints

    This is the main interface for checkpoint saving in core training.
    Stage managers can use this function or implement their own logic.

    Uses config from outside checkpoint section:
        - max_steps: Total training steps

    Args:
        step: Current training step
        model: FSDP-wrapped model
        optimizers: List of optimizers
        config: Full training configuration dict (reads config['checkpoint'])
        rank: Current rank
        world_size: Total number of ranks
        dataloader_state: Optional dataloader state for resuming
        trainer_state: Optional trainer internal state (EMA loss, timing, etc.)
    """
    # Extract checkpoint config and max_steps
    checkpoint_config = config.get('checkpoint', {})
    max_steps = config['max_steps']

    # Extract checkpoint settings
    save_dir = os.path.expandvars(checkpoint_config['save_dir'])
    save_every = checkpoint_config['save_every']
    keep_last_n = checkpoint_config['keep_last_n']

    # Check if we should save
    if not should_save_checkpoint(step, max_steps, save_every):
        return

    # Save checkpoint
    ckpt_dir = os.path.join(save_dir, f"step_{step:06d}")

    # Delete existing checkpoint directory to avoid overwrite warnings
    # Only rank 0 performs the deletion
    if rank == 0 and os.path.exists(ckpt_dir):
        shutil.rmtree(ckpt_dir)

    # Wait for rank 0 to finish deletion before all ranks proceed
    if world_size > 1:
        torch.distributed.barrier()

    meta_data = {'step': step}
    # (model_config recording lives in save_checkpoint_dcp — the ONE writer —
    #  as the full asdict of model.config, so every save path gets the complete
    #  architecture. A partial 4-field copy used to live here; it shadowed the
    #  full record and a from-meta rebuild then filled geometry from defaults.)

    # Add trainer internal state if provided
    if trainer_state:
        meta_data['trainer_state'] = trainer_state

    save_checkpoint_dcp(
        checkpoint_dir=ckpt_dir,
        model=model,
        optimizers=optimizers,
        meta_data=meta_data,
        rank=rank,
        world_size=world_size,
        dataloader_state=dataloader_state,
    )

    # Print and cleanup (only on rank 0)
    if rank == 0:
        from core.utils import print0
        loader_info = f" | {dataloader}" if dataloader is not None else ""
        print0(f"✓ Checkpoint saved: {ckpt_dir}{loader_info}")
        cleanup_old_checkpoints(save_dir, keep_last_n, current_step=step)
