defaults:
  - base
  - _self_

compile: false
device_batch_size: 8
total_batch_size: 128
max_steps: 20
optimizer:
  scheduler:
    warmup_steps: 2
evaluation:
  subset_size: 8
  interval_steps: 10
  full_interval_steps: 20
  full_validation: false
  gen_batch_size: 4
  train_diagnostic_size: 8
checkpoint:
  save_every: 10
logging:
  log_every: 1
